In [3]:
import requests
import pandas as pd
from bs4 import BeautifulSoup

In [78]:
url = 'https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M'
response = requests.get(url)
soup = BeautifulSoup(response.text,'lxml')

###  Assume the target table is the 1st table in that web page

In [79]:
table = soup.find('table')
rows = table.find_all('tr')
head = table.find_all('th')

In [80]:
col = []
col_name = [ele.text.strip() for ele in head]
for ele in col_name:
    col.append((ele,[]))

In [81]:
for i in range(1,len(rows)):
    T = rows[i]
    c = 0
    for j in T.find_all('td'):
        ctnt = j.text.strip()
        col[c][1].append(ctnt)
        c +=1

In [82]:
Dict = {col:data for (col,data) in col}
df = pd.DataFrame(Dict)
df.head(10)

  Postcode           Borough     Neighbourhood
0      M1A      Not assigned      Not assigned
1      M2A      Not assigned      Not assigned
2      M3A        North York         Parkwoods
3      M4A        North York  Victoria Village
4      M5A  Downtown Toronto      Harbourfront
5      M5A  Downtown Toronto       Regent Park
6      M6A        North York  Lawrence Heights
7      M6A        North York    Lawrence Manor
8      M7A      Queen's Park      Not assigned
9      M8A      Not assigned      Not assigned

In [83]:
df = df[df['Borough']!='Not assigned']
df.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Not assigned
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [87]:
df.loc[df['Neighbourhood']=='Not assigned','Neighbourhood'] = df['Borough']
df.head(10)

   Postcode           Borough     Neighbourhood
2       M3A        North York         Parkwoods
3       M4A        North York  Victoria Village
4       M5A  Downtown Toronto      Harbourfront
5       M5A  Downtown Toronto       Regent Park
6       M6A        North York  Lawrence Heights
7       M6A        North York    Lawrence Manor
8       M7A      Queen's Park      Queen's Park
10      M9A         Etobicoke  Islington Avenue
11      M1B       Scarborough             Rouge
12      M1B       Scarborough           Malvern

In [92]:
df2 = df.groupby(['Postcode','Borough'],sort=False).agg(', '.join)
df2.reset_index(inplace=True)
df2.head(10)

  Postcode           Borough                     Neighbourhood
0      M3A        North York                         Parkwoods
1      M4A        North York                  Victoria Village
2      M5A  Downtown Toronto         Harbourfront, Regent Park
3      M6A        North York  Lawrence Heights, Lawrence Manor
4      M7A      Queen's Park                      Queen's Park
5      M9A         Etobicoke                  Islington Avenue
6      M1B       Scarborough                    Rouge, Malvern
7      M3B        North York                   Don Mills North
8      M4B         East York   Woodbine Gardens, Parkview Hill
9      M5B  Downtown Toronto          Ryerson, Garden District

In [93]:
df2.shape

(103, 3)